name: Deploy Website

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'
      - 'install-remote.sh'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: website
      run: |
        rm -f pnpm-lock.yaml
        pnpm install

    - name: Build website
      working-directory: website
      run: pnpm build

    - name: Deploy to Bunny CDN
      uses: R-J-dev/bunny-deploy@v2.0.3
      with:
        access-key: ${{ secrets.BUNNY_API_KEY }}
        directory-to-upload: "./website/dist"
        storage-endpoint: "https://storage.bunnycdn.com"
        storage-zone-name: ${{ secrets.BUNNY_STORAGE_ZONE }}
        storage-zone-password: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
        concurrency: "50"
        enable-delete-action: true
        enable-purge-pull-zone: true
        pull-zone-id: ${{ secrets.BUNNY_PULL_ZONE_ID }}
        replication-timeout: "15000"