name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            cc: gcc

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwayland-dev \
          wayland-protocols \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          pkg-config \
          make

    - name: Build
      env:
        CC: ${{ matrix.cc }}
      run: |
        make clean
        make
        
    - name: Create binary name
      id: binary
      run: |
        echo "name=hyprlax-${{ matrix.arch }}" >> $GITHUB_OUTPUT

    - name: Rename binary
      run: |
        mv hyprlax ${{ steps.binary.outputs.name }}
        chmod +x ${{ steps.binary.outputs.name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.binary.outputs.name }}
        path: ${{ steps.binary.outputs.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./binaries

    - name: Prepare release files
      run: |
        # Move all binaries to root
        find ./binaries -type f -name 'hyprlax-*' -exec mv {} . \;
        
        # Check if we have the x86_64 binary
        if [ ! -f hyprlax-x86_64 ]; then
          echo "Error: x86_64 binary not found!"
          exit 1
        fi
        
        # Create checksums
        sha256sum hyprlax-* > SHA256SUMS
        
        # List files for verification
        ls -la hyprlax-* SHA256SUMS

    - name: Extract version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate release notes
      id: notes
      run: |
        # Get commits since last tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREV_TAG" ]; then
          echo "notes=Initial release of hyprlax" >> $GITHUB_OUTPUT
        else
          NOTES=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s" | head -20)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        body: |
          ## Release ${{ steps.version.outputs.version }}
          
          Smooth parallax wallpaper animations for Hyprland.
          
          ### Installation
          
          Download the binary:
          - `hyprlax-x86_64` - For x86_64 systems
          
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/hyprlax-x86_64
          chmod +x hyprlax-x86_64
          sudo mv hyprlax-x86_64 /usr/local/bin/hyprlax
          ```
          
          For ARM64 and other architectures, please build from source.
          
          ### Changes
          
          ${{ steps.notes.outputs.notes }}
          
          ### Checksums
          
          Verify your download with SHA256SUMS file.
          
        files: |
          hyprlax-x86_64
          SHA256SUMS
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}